# Generated by Django 3.1.7 on 2021-05-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_product',
            name='user_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
