# Generated by Django 3.1.7 on 2021-05-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210521_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_product',
            name='active',
        ),
    ]
