# Generated by Django 3.1.7 on 2021-05-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_my_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='my_balance',
            options={},
        ),
        migrations.AlterField(
            model_name='my_balance',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
