# Generated by Django 3.1.7 on 2021-05-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20210525_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_balance',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
